### PR TITLE
Ready for packagist.org

### PR DESCRIPTION
**Pull request by AJenbo**
This pull request accomplishes the following:
PHP 7.1 support.
Union types.
Analyze and use types found in function signature.
Align and group the generated phpDoc parameters.
Use proper type names.
Add support for float type.
Modernize the code to use PRS-4 auto-loading.
Port tests to phpunit (note 3 tests are disabled, partial parsing isn't supported any more).
Fixed some edge cases.
Add phpDoc and type-hinting to the code base.

### CODE REVIEW

**Comment by troelskn** [comment]
- Why use camelCase for `bin/PHPTracerWeaver`? Doesn't seem like a common convention for shell scripts.
- Move `trace.sh` in `bin/` as well.

**Comment by AJenbo** [comment]
@troelskn any other changes you would like done to this before it is ready for merge?

**Comment by troelskn** [comment]
Don't think so. Good to see this project coming back up to speed.

**Comment by AJenbo** [comment]
Ok, if you merge it I think I am about ready with the next batch of changes :)

**Pull request merged**
