### PR TITLE
Use Symfony Console Component for CLI interface

### PR DESCRIPTION
**Pull request by AJenbo**
Replace php-trace-weaver and trace.sh exec's with a common symfony/console based exec.
Add a progress bar.
Switch to computer frindly traceformat.
Richer types detection (especial for input and arrays).
Replace the destination path with --overwrite.
Allow source path to be a folder rather then a single file.
Make source path an array, allowing for multiple paths.
Add option to --append to trace file instead of overwriting it.
Add option to specefy --tracefile path.
Rename tool to phpweaver.

### CODE REVIEW

**Comment by AJenbo** [comment]
Personally I would prefer having the --overwrite switch on by default and add a --print option instead, but i wanted your input before changing behavior.

Also the trace command is a little odd in regards to the additional options to pass to the sub-process. It should start with a space, the reason for this is that symfony/console seams to get confused if an argument start with a dash (-). Wondering if you have a better idea for how to handle this. Possibly we could just have the command as a single input string, script path and parameters all in one:
`phpweaver trace "vendor/bin/phpunit -c tests/phpunit.xml"`
Current is:
`phpweaver trace vendor/bin/phpunit " -c tests/phpunit.xml"`

**Comment by troelskn** [comment]
With regards to the last part, it should be possible to use `--` to stop options parsing, e.g.:
`phpweaver trace -- vendor/bin/phpunit "-c tests/phpunit.xml"`

**Comment by troelskn** [comment]
As for `--overwrite`, I agree that it makes sense to enable by default. I don't think we should be concerned about breaking existing behaviour at this point, so just make the change.

**Comment by AJenbo** [comment]
Thanks didn't know about --, that solved it (sample included in the help message).

Also I removed the --overwrite option. I can add the --print option, but it doesn't seam like any of the similar tools have an option like that.

**Comment by troelskn** [comment]
Documentation still mentions `--override`. Also, perhaps we should document that one can use `--`. It's a standard bash feature, but it's not given that everyone will know about it.

Would also be good to update the meagre example to use the new bin tool.

And could you rebase on master.

**Comment by AJenbo** [comment]
Finally got around to looking at this (started a job with a new company), I have resolved the merge conflict and updated the documentation. If you prefer I can still re-base on current master, if you prefer having a clean commit history.

**Comment by troelskn** [comment]
Loos good -- I don't feel strongly about rebase vs. merge, so feel free to do either.

**Pull request merged**
